### ISSUE TITLE
Specifying Duration::MAX as TTL leads to addition with overflow panic

### ISSUE THREAD

**Issue by wez** [losfair/sqlite-cache#1]
When attempting to set an entry with the maximum possible TTL, sqlite-cache will panic:

```
topic.set("key", value, std::time::Duration::MAX);
```

I can work around this by using an arbitrary value like 300 days worth.
I think the panic should at least be an Err variant so that the program doesn't terminate in surprising situations, such as when setting a TTL based on a max-age cache header returned from some external source.

**Comment by losfair** [comment]
I implemented a fix in https://github.com/losfair/sqlite-cache/pull/2. Now the TTL and expiration time will saturate to `i64::MAX` seconds to fit in a SQLite integer column.

Please check whether this solves the issue :)

**Comment by wez** [comment]
Confirmed, thanks!

**Comment by losfair** [comment]
Released v0.1.3 with this fix.
